version: '3.1'

services:
  python:
    build: .
    container_name: test_work
    volumes:
      - .:/usr/src/app
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTHRES_USER: postgres
      POSTGRES_PASSWORD: 3991
    container_name: db


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "5432"